created button for token generation
the-collab-lab/tcl-50-smart-shopping-list pull request #19
Opened 2022-10-12 15:03 UTC by mide358

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description
This PR adds the `@the-collab-lab/shopping-list-utils` as a dependency to the project and also adds a button to the Home component which when clicked generates a three-word-token.

### Added `Create a new list` Button to Home component
A 'create a new list'  button was added to the home component. If clicked, it will generate a three-word-token that is stored in the localStorage using the setListToken function in App.jsx
If the user already has a token, the user is automatically redirected to the List view.
## Related Issue

## Acceptance Criteria

## Type of Changes

- [ ] `@the-collab-lab/shopping-list-utils` is added as a dependency to the project.
- [ ] The string `my test list` in `App.jsx` is replaced with `null`, so users are not automatically subscribed to any list.

If a user doesn’t already have a token:

- [ ] A button in the `Home` component allows them to create a new list
- [ ] Clicking the button generates a new token and saves it to `localStorage` using the `setListToken` function in `App.jsx`.
- [ ] Once the token has been created and saved, the user is redirected to the `List` view.
if a user does already have a token:

- [ ] They are automatically redirected to the `List` view.

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

### After

## Testing Steps / QA Criteria
From your terminal, pull down this branch with `git pull origin ia-kl-new-shopping-list` and check that branch out with 
`git checkout  ia-kl-new-shopping-list`
Then run `npm i @the-collab-lab/shopping-list-utils`  to install the newly added dependency locally.
 Run npm start to launch the app.

Click on the `Create a new list` button to generate a token. (Note that the token is only visible in the local storage)
You will be redirected to the `List` page.

2022-10-13 10:39 UTC, vicowiti approved these changes

2022-10-13 16:32 UTC, michhub-dev approved these changes
Everything is working fine.

2022-10-13 21:37 UTC, redapy requested changes
Excellent work team, the feature works as expected and AC is fulfilled.
I have just a tiny note when I try to navigate back to the home page (after the token is saved in my local storage) there is a quick flash (the 'generate token' button shows up in a sec). I left some comments that could be a solution!

2022-10-13 21:37 UTC, redapy commented on src/App.jsx
> +					/>
you can redirect the user directly from here, with the `<Navigate />` component, without passing the `listToken` to the home page. `element={listToken ? <Navigate to="/list" /> :  <Home onClick={handleClick} />}` 
- Note: This is a one way to fix the flash, maybe there are other solutions.

2022-10-13 21:37 UTC, redapy commented on src/views/Home.jsx
> +	}, [listToken, navigate]);
If you use the `<Navigate />` component, you can just delete this.

2022-10-14 05:30 UTC, klezi10 commented
Thanks @redapy that's really good advice, using even less code!

2022-10-14 15:34 UTC, redapy approved these changes

2022-10-15 11:51 UTC, merged