Ia styling home page
the-collab-lab/tcl-50-smart-shopping-list pull request #48
Opened 2022-11-24 07:46 UTC by mide358

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

The home page have been styled to look like the figma design

## Related Issue
Closes #47 

## Acceptance Criteria
 [x] The home page is styled  to have a great look as the [figma design](https://www.figma.com/file/WDYjT265wEzdRlEXKTrclx/smart-Shopping-List?node-id=9%3A112&t=NbWcc8vO8RbuKgAy-0)

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before
# Desktop
![image](https://user-images.githubusercontent.com/51176311/203722733-3aff8bf6-b813-49f6-9fc8-afff7a3ce66c.png)

# Mobile
![image](https://user-images.githubusercontent.com/51176311/203722544-337b21b5-62f2-42eb-b220-4fee65bb1ee2.png)

### After
# Desktop
![image](https://user-images.githubusercontent.com/51176311/203722266-b4e9fdeb-c779-4a6f-a8a2-5fe481047665.png)

# Mobile
![image](https://user-images.githubusercontent.com/51176311/203722382-a3099be9-a6c0-4d05-900c-d9da19b4e902.png)

## Testing Steps / QA Criteria

1. From your terminal, do `git checkout main`
2. Pull down this branch with `git pull origin ia-styling-home-page`
3. Checkout the branch with `git checkout ia-styling-home-page`
4. See changes in desktop and mobile version

2022-11-24 12:28 UTC, vicowiti requested changes
Great work, I think we should maintain a max height of 100vh. Using styles like `h-screen` or h-[100vh]. so that the user sees all parts of the landing page .  Since its a global issue, we should work on it when refactoring

2022-11-24 12:37 UTC, vicowiti approved these changes

2022-11-24 14:49 UTC, klezi10 requested changes

2022-11-24 14:49 UTC, klezi10 commented on src/views/Home.jsx
> +				"
I think 32px for text is too big. This is what I see in the browser
![image](https://user-images.githubusercontent.com/74952593/203812116-d40d0410-3b99-4c3d-95ae-5e531ecd34b9.png)

2022-11-24 16:53 UTC, klezi10 approved these changes

2022-11-24 20:39 UTC, michhub-dev approved these changes

2022-11-25 19:07 UTC, redapy requested changes
Great Work! I have a non-blocking note/suggestion, try to not use extra classes for styles when you have a unique HTML element that you can use as a CSS selector.
Here's some examples: 
- `.Layout-header` => header
- `.Layout-header > h1` => header > h1
-  `.Layout-main` => main
- `.Nav` => nav
- `.Nav-link` => nav > a.   (here it's okay to use a class, I'm just giving examples)

2022-11-25 19:07 UTC, redapy commented on src/views/Layout.css
>  .Layout-header > h1 {
Just a convention, the class names start with lowercase.

2022-11-25 19:41 UTC, redapy approved these changes

2022-11-25 19:43 UTC, merged